CREATE TABLE cars (
car_id INT PRIMARY KEY,
make VARCHAR(50),
type VARCHAR(50),
style VARCHAR(50),
cost_$ INT
);

INSERT INTO cars (car_id, make, type, style, cost_$)
VALUES (1, 'Honda', 'Civic', 'Sedan', 30000),
(2, 'Toyota', 'Corolla', 'Hatchback', 25000),
(3, 'Ford', 'Explorer', 'SUV', 40000),
(4, 'Chevrolet', 'Camaro', 'Coupe', 36000),
(5, 'BMW', 'X5', 'SUV', 55000),
(6, 'Audi', 'A4', 'Sedan', 48000),
(7, 'Mercedes', 'C-Class', 'Coupe', 60000),
(8, 'Nissan', 'Altima', 'Sedan', 26000);

CREATE TABLE salespersons (
salesman_id INT PRIMARY KEY,
name VARCHAR(50),
age INT,
city VARCHAR(50)
);

INSERT INTO salespersons (salesman_id, name, age, city)
VALUES (1, 'John Smith', 28, 'New York'),
(2, 'Emily Wong', 35, 'San Fran'),
(3, 'Tom Lee', 42, 'Seattle'),
(4, 'Lucy Chen', 31, 'LA');

CREATE TABLE sales (
sale_id INT PRIMARY KEY,
car_id INT,
salesman_id INT,
purchase_date DATE,
FOREIGN KEY (car_id) REFERENCES cars(car_id),
FOREIGN KEY (salesman_id) REFERENCES salespersons(salesman_id)
);

INSERT INTO sales (sale_id, car_id, salesman_id, purchase_date)
VALUES (1, 1, 1, '2021-01-01'),
(2, 3, 3, '2021-02-03'),
(3, 2, 2, '2021-02-10'),
(4, 5, 4, '2021-03-01'),
(5, 8, 1, '2021-04-02'),
(6, 2, 1, '2021-05-05'),
(7, 4, 2, '2021-06-07'),
(8, 5, 3, '2021-07-09'),
(9, 2, 4, '2022-01-01'),
(10, 1, 3, '2022-02-03'),
(11, 8, 2, '2022-02-10'),
(12, 7, 2, '2022-03-01'),
(13, 5, 3, '2022-04-02'),
(14, 3, 1, '2022-05-05'),
(15, 5, 4, '2022-06-07'),
(16, 1, 2, '2022-07-09'),
(17, 2, 3, '2023-01-01'),
(18, 6, 3, '2023-02-03'),
(19, 7, 1, '2023-02-10'),
(20, 4, 4, '2023-03-01');


 /*01. What are the details of all cars purchased in the year 2022?*/

 SELECT
	sales.car_id,
	purchase_date,
	make,
	type,
	style,
	cost_$ 
 FROM 
	sales
 JOIN
	cars ON cars.car_id = sales.car_id
 WHERE
	YEAR(sales.purchase_date) ='2022'
 ORDER BY
	purchase_date DESC;

 /*02. What is the total number of cars sold by each salesperson?*/

 SELECT 
	salespersons.salesman_id,
	name,
	COUNT(sales.sale_id) AS total_no_of_cars_sold
 FROM 
	salespersons
 JOIN 
	sales ON sales.salesman_id = salespersons.salesman_id
 GROUP BY
	salespersons.salesman_id,
	name
 ORDER BY 
	total_no_of_cars_sold DESC;

 /*03. What is the total revenue generated by each salesperson?*/

 SELECT 
	salespersons.salesman_id,
	name,
	SUM(cost_$) AS total_revenue_generated
 FROM 
	salespersons
 JOIN 
	sales
		ON sales.salesman_id = salespersons.salesman_id
 JOIN
	cars
		ON cars.car_id = sales.car_id
 GROUP BY
	salespersons.salesman_id,
	name
 ORDER BY 
	total_revenue_generated DESC;

 /*04. What are the details of the cars sold by each salesperson? */

 SELECT
	cars.car_id,
	make,
	type,
	style,
	cost_$,
	purchase_date,
	name AS salesman
 FROM
	cars
 JOIN
	sales ON cars.car_id = sales.car_id
 JOIN
	salespersons ON salespersons.salesman_id =sales.salesman_id
 ORDER BY car_id;

 /*05. What is the total revenue generated by each car type?*/

 SELECT 
	type AS car_type,
	SUM(cost_$) AS total_revenue_generated
 FROM
	cars
 GROUP BY
	type
 ORDER BY total_revenue_generated DESC;

 /*06. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?*/

 SELECT
	sales.car_id,
	make,
	type,
	style,
	cost_$ AS total_revenue_generated
 FROM 
	sales
 JOIN
	cars ON cars.car_id = sales.car_id
 JOIN
	salespersons ON salespersons.salesman_id = sales.salesman_id
 WHERE
	YEAR(sales.purchase_date) ='2021'
	AND
	salespersons.name = 'Emily Wong'
 ORDER BY
	total_revenue_generated DESC;


 /*07. What is the total revenue generated by the sales of hatchback cars?*/

  SELECT 
	style,
	SUM(cost_$) AS total_revenue_generated
  FROM
	cars
  JOIN
	sales ON cars.car_id = sales.car_id
  WHERE 
	style = 'Hatchback'
  GROUP BY
	style;

/*08. What is the total revenue generated by the sales of SUV cars in the year 2022?*/

  SELECT 
	style,
	SUM(cost_$) AS total_revenue_generated
  FROM
	cars
  JOIN
	sales ON cars.car_id = sales.car_id
  WHERE 
	style = 'SUV' AND
	YEAR(purchase_date) = '2022'
  GROUP BY
	style;

/*09. What is the name and city of the salesperson who sold the most number of cars in the year 2023?*/

 SELECT TOP 1
	name,
	city,
	COUNT(name) AS number_of_cars_sold
 FROM
	salespersons
 JOIN sales ON sales.salesman_id = salespersons.salesman_id
 WHERE 
	YEAR(purchase_date) = '2023'
 GROUP BY
	name, city
 ORDER BY
	number_of_cars_sold DESC;

 /*10. What is the name and age of the salesperson who generated the highest revenue in the year 2022? */

 SELECT TOP 1
	name,
	age,
	SUM(cost_$) AS highest_revenue
 FROM
	salespersons
 JOIN sales ON sales.salesman_id = salespersons.salesman_id
 JOIN cars ON sales.car_id = cars.car_id
 WHERE
	YEAR(purchase_date) ='2022'
 GROUP BY
	name, age
 ORDER BY highest_revenue DESC;
